language: go
go:
  - tip
script:
  - go get github.com/cloudflare/cf-tls/tls
  - go test github.com/cloudflare/cf-tls/tls 
notifications:
  email:
    recipients:
    - jacob@cloudflare.com
    on_success: never
